spring.application.name=Fitsense

spring.datasource.url=jdbc:postgresql://ep-plain-scene-acbn96z0-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.placeholder-replacement=false

authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=7

fitsense.ai.enabled=${FITSENSE_AI_ENABLED:true}
fitsense.ai.api-token=${REPLICATE_API_TOKEN:}

fitsense.ai.base-url=https://api.replicate.com/v1/models/openai/gpt-5-structured/predictions
fitsense.ai.model=${FITSENSE_AI_MODEL:gpt-5-nano}
fitsense.ai.reasoning-effort=${FITSENSE_AI_REASONING_EFFORT:medium}
fitsense.ai.timeout-seconds=150

fitsense.volume.duration-to-reps-divisor=30